### ISSUE TITLE
[1.12.2] Wolf equipment does not display on spirit wolves

### ISSUE THREAD

**Issue by ataylor-design** [satyrnidae/wolfarmor-legacy#170]
**Issue Description**
Spirit wolves from Electroblob's Wizardry equipped with Wolf Armor and Storage's items do not display armor or chests on their model.

**Relevant Mods**
[Electroblob's Wizardry](https://github.com/Electroblob77/Wizardry)

**Reproduction Steps**
1. Summon a Spirit Wolf, either by using a wand with the spell equipped, or a scroll.
2. Equip the spirit wolf with armor or chest.

**Expected Behavior**
Spirit Wolves equipped with armor or storage should reflect this on their model.

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/45052816/98285834-f94b2780-1f57-11eb-9f5e-901c1864d526.png)

**Version Information:**
 - OS: Windows 10
 - Java: Java 8
 - Minecraft Version: 1.12.2
 - Mod Version: 3.7.5
 - Forge Version: 14.23.5.2854

**Additional Context**
Visual only; armor and storage work as expected otherwise. Bug reproduced in a Minecraft instance with only Wizardry and Wolf Armor and Storage installed.

**Comment by Gremlinfot** [comment]
I have the same issue, but with TFC wolves.

**Comment by satyrnidae** [comment]
I'll investigate adding compatibility layers for these mods.

**Comment by satyrnidae** [comment]
Well... I got the compatibility layer working, but there is a GL blend issue somewhere which is causing the wolf armor layers to glow when Wizardry is installed. Been banging my head on it for like six hours or so tho and getting nowhere, so I will open a new issue for the glowing layers
