### ISSUE TITLE
[1.12.2] Mixin fails due to BeforeFinalReturn on a ctor

### ISSUE THREAD

**Issue by FrostiFur** [satyrnidae/wolfarmor-legacy#175]
Game fails to load and crashes with Exit Code 0 with liteloader installed. Able to launch with Wolf Armor if I have normal forge launch instead of Forge+Liteloader.
Attached a log a recent log with the issue involved.

 - OS: Windows 10
 - Java: Jave 8(i think)
 - Minecraft Version: 1.12.2
 - Forge Version:14.23.5.2854
 - Mod Version: 1.12.2 3.7.5

[2020-12-14-2.log](https://github.com/satyrnidae/wolfarmor/files/5692330/2020-12-14-2.log)

**Comment by satyrnidae** [comment]
duplicates #165

**Comment by satyrnidae** [comment]
whoops should have looked more closely at that log
this one is slightly different
