### ISSUE TITLE
[3.7.5-1.12.2] crash on startup with sophisticated wolves.

### ISSUE THREAD

**Issue by xelotex** [satyrnidae/wolfarmor-legacy#178]
**Issue Description**
A clear and concise description of the issue.

**Relevant Mods**
A list or a link to a list of other mods relevant to the issue.

**Reproduction Steps**
2. Interact with '....'
3. Place '....'

**Expected Behavior**

**Screenshots / Videos**
If applicable, add screenshots or videos to help explain your problem.

**Version Information:**
 - OS: Windows.
 - Java: Java 8.
 - Minecraft Version: 1.12.2
 - Mod Version: 3.7.5

[crash-2021-02-07_11.55.39-client.txt](https://github.com/satyrnidae/wolfarmor/files/5939661/crash-2021-02-07_11.55.39-client.txt)

**Comment by satyrnidae** [comment]
Known issue with Sophisticated Wolves; it is using an outdated API. See https://github.com/NightKosh/Sophisticated-wolves/pull/90

**Comment by xelotex** [comment]
> Known issue with Sophisticated Wolves; it is using an outdated API. See [NightKosh/Sophisticated-wolves#90](https://github.com/NightKosh/Sophisticated-wolves/pull/90)

wait, ¿what do i need to do to fix this issue?

**Comment by satyrnidae** [comment]
unfortunately until that linked pull request is accepted and a new version is released, Sophisticated Wolves and Wolf Armor and Storage are not currently compatible

**Comment by xelotex** [comment]
> unfortunately until that linked pull request is accepted and a new version is released, Sophisticated Wolves and Wolf Armor and Storage are not currently compatible

it's not compatible with the latest versions of wolf armor (or upside down) but there's any old version of your mod that could be compatible with sophisticated wolves?

**Comment by satyrnidae** [comment]
any v2 release should work (file will be named like wolfarmor-1.12.2-2.x.x.x).  These versions aren't supported any longer, but they may work

**Comment by xelotex** [comment]
> any v2 release should work (file will be named like wolfarmor-1.12.2-2.x.x.x). These versions aren't supported any longer, but they may work

thanks

**Comment by CovertJaguar** [comment]
Actually, after compiling the PR myself, the game *still* crashes with this error.

I suspect it related to this code: https://github.com/satyrnidae/wolfarmor/blob/master/src/main/java/dev/satyrn/wolfarmor/compatibility/sophisticatedwolves/SophisticatedWolvesProvider.java

**Comment by CovertJaguar** [comment]
For reference, I can confirm that running Sophisticated Wolves 3.13.9 (with the Wolf Armor compat code stripped) works flawlessly with Wolf Armor 3.4.1.1. Pet Carrier works, treats work, everything seems to work. 

Contrast that to version 3.7.5 of Wolf Armor, which crashes on startup with any version of SW.

**Comment by satyrnidae** [comment]
Additional investigation revealed that the entire compatibility layer wasn't working right on servers or with sophisticated wolves at all. Should be fixed presently.

**Comment by satyrnidae** [comment]
Fixed by 73e2081 and ceaf9bd
